apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stock-trading
resources:
  - serviceaccount.yaml
  - configmap.yaml
  - secret-example.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/sinhnguyen1411/stock-trading/user-service
    newTag: dev
