apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cosign-public-key.yaml
  - clusterpolicy-verify-images.yaml
  - clusterpolicy-cve-threshold.yaml
  - clusterpolicy-require-sbom.yaml
